core/urls.py
from django.urls import path

from . import views, views_managers_locations, views_users_addons

app_name = 'core'
urlpatterns = [
    path('', views.main, name='main'),
    path('main', views.main, name='main'),
    path('edit_sachnr/<str:sachnr>', views.edit_sachnr, name='edit_sachnr'),
    path('delete_sachnr/<int:pk>', views.delete_sachnr, name='delete_sachnr'),
    path('disponent_all/', views.disponent_all, name='disponent_all'),
    path('edit_disponent/<int:pk>', views.edit_disponent, name='edit_disponent'),
    path('delete_disponent/<int:pk>', views.delete_disponent, name='delete_disponent'),
    path('serialize_sachnr/', views.serialize_sachnr, name='serialize_sachnr'),
    path('sachnr_detailed_view/', views.sachnr_select_detailed_view, name='sachnr_select_detailed_view'),
    path('sachnr_details/<int:pk>', views.sachnr_details, name='sachnr_details'),
    path('import', views.import_data, name='import_data'),
    path('dispo_all', views.dispo_all, name='dispo_all'),
    path('dispo_delete/<int:pk>', views.dispo_delete, name='dispo_delete'),
    path('edit_dispo/<int:pk>', views.edit_dispo, name='edit_dispo'),
    path('serialize_deliverer/', views.serialize_deliverer, name='serialize_deleverer'),
    # managers_locations
    path('edit_responsible/<int:pk>', views_managers_locations.edit_responsible, name='edit_responsible'),
    path('responsible_all', views_managers_locations.responsible_all, name='responsible_all'),
    path('delete_responsible/<int:pk>', views_managers_locations.delete_responsible, name='delete_responsible'),
    path('location_all', views_managers_locations.location_all, name='location_all'),
    path('location_delete/<int:pk>', views_managers_locations.location_delete, name='location_delete'),
    path('edit_location/<int:pk>', views_managers_locations.edit_location, name='edit_location'),
    # users_addons
    path('pers_numbers', views_users_addons.pers_numbers, name='pers_numbers'),
    path('edit_pers_number/<int:pk>', views_users_addons.edit_pers_number, name='edit_pers_numbers'),
    path('delete_pers_number/<int:pk>', views_users_addons.delete_pers_number, name='delete_pers_number'),
    path('users_serialize', views_users_addons.users_serialize, name='users_serialize'),
    path('users_temp_serialize', views_users_addons.users_temp_serialize, name='users_temp_serialize'),
    path('NewUserS1', views_users_addons.NewUserS1, name='NewUserS1'),
    path('NewUserS2/<str:shortsign>', views_users_addons.NewUserS2, name='NewUserS2'),
    path('NewUserS3/<str:shortsign>', views_users_addons.NewUserS3, name='NewUserS3'),
    path('NewAccount/<str:shortsign>/<str:manager>', views_users_addons.NewAccount, name='NewAccount'),
    path('AddCompany/<str:shortsign>/<str:operator>', views_users_addons.AddCompany, name='AddCompany'),
    path('AddPersNumber/<str:shortsign>/<str:pers_number>', views_users_addons.AddPersNumber,
         name='AddPersNumber'),
    path('SaveCard/<str:shortsign>/<str:card>', views_users_addons.SaveCard, name='SaveCard'),
    path('PrintCard/<str:shortsign>', views_users_addons.PrintCard, name='PrintCard'),
    path(
        'SetLastDay/<str:shortsign>/<last_day>/<first_day>', views_users_addons.SetLastDay, name='SetLastDay'),
    # suppliers
    path('serialize_supplier', views.serialize_supplier, name='serialize_supplier'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('dashboard', views.dashboard, name='dashboard'),
]

django3_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', dashboard_views.dashboard, name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('instructions/', include('instructions.urls')),
    path('canteen/', include('canteen.urls')),
    path('hr_working_hours/', include('hr_working_hours.urls')),
    path('hardware/', include('hardware.urls')),
    path('core/', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]


# sachnr & tabela brakow
class Dispo(models.Model):
    name = models.CharField(max_length=25)
    ekg = models.CharField(max_length=25, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'dispo'
        app_label = 'core'

    def __str__(self):
        return self.name, self.ekg


class Disponent(models.Model):
    dispo = models.ManyToManyField(Dispo)
    shortsign = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))

    class Meta:
        verbose_name_plural = 'responsible'
        app_label = 'core'

    def __str__(self):
        return '%s %s' % (self.dispo, self.shortsign)


class Sachnr(models.Model):
    sachnr = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=200)
    dispo = models.ForeignKey(Dispo, null=True, on_delete=models.SET(get_sentinel_user))
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Sachnummer'
        permissions = (
            ("view_core", "Can see app"),
            ("can_search_for_sachnr", "Can search for sachnr")
        )
        app_label = 'core'

    def __str__(self):
        return self.sachnr, self.description, (self.dispo.name, self.dispo.ekg)


class Deliverer(models.Model):
    number = models.CharField(max_length=150, blank=False)
    name = models.CharField(max_length=250, blank=False)

    class Meta:
        verbose_name_plural = 'deliverers'
        permissions = (
            ("view_core", "Can see app"),
        )
        app_label = 'core'

    def __str__(self):
        return self.number, self.name


class Supplier(models.Model):
    name = models.CharField(max_length=250, blank=False)

    class Meta:
        verbose_name_plural = 'Suppliers'
        app_label = 'core'

    def __str__(self):
        return '%s' % self.name


class Location(models.Model):
    location = models.CharField(max_length=150)
    detailed_location = models.CharField(max_length=250, null=True)

    class Meta:
        verbose_name_plural = 'core_location'
        app_label = 'core'
        permissions = (
            ("edit_location", "Can edit location"),
        )

    def __str__(self):
        return '%s %s' % (self.location, self.detailed_location)

hr_working_hours/models.py
# -*- coding: utf-8 -*-
from django.db import models
from core.models import Location
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


class RegisterManager(models.Manager):
    def get_by_natural_key(self, card, timestamp):
        return self.get(card=card, TimeStampIn=timestamp)


class TimeRegister(models.Model):
    card = models.CharField(max_length=255)
    TimeStampIn = models.DateTimeField(null=True, blank=True)
    TimeStampOut = models.DateTimeField(null=True, blank=True)
    uploaded = models.BooleanField(default=False)

    objects = RegisterManager()

    def natural_key(self):
        return self.card, self.TimeStampIn

    class Meta:
        managed = True
        db_table = 'register_timeregister'
        verbose_name_plural = 'Time Register'
        unique_together = [['card', 'TimeStampIn']]
        app_label = 'hr_working_hours'

    def __str__(self):
        return self.card, self.TimeStampIn, self.uploaded


class HolidayTypes(models.Model):
    type = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        app_label = 'hr_working_hours'
        verbose_name_plural = 'Holiday Types'
        permissions = (
            ("view_holiday_types", "Can see Holiday Types"),
        )

    def __str__(self):
        return '%s %s' % (self.type, self.description)


class WorkingHours(models.Model):
    source_id = models.BigIntegerField(null=True, unique=True)
    card = models.CharField(max_length=255)
    shortsign = models.CharField(max_length=255, null=True)
    entry_time = models.DateTimeField(null=True)
    leaving_time = models.DateTimeField(null=True)
    accepted = models.BooleanField(default=False)
    total_time = models.DurationField(null=True, blank=True)
    extra_time = models.DurationField(null=True, blank=True)
    holiday = models.BooleanField(default=False)
    accepted_by = models.CharField(max_length=100, null=True, blank=True)
    holiday_type = models.ForeignKey(HolidayTypes, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        app_label = 'hr_working_hours'
        verbose_name_plural = 'Working Hours'
        permissions = (
            ("view_working_hours", "Can see Working Hours"),
            ("can_draw_report", "Can draw a report")
        )

    def __str__(self):
        return '%s %s %s %s' % (self.source_id, self.card, self.entry_time, self.leaving_time)


class LocationToManager(models.Model):
    location = models.ManyToManyField(Location)
    manager = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    class Meta:
        app_label = 'hr_working_hours'
        verbose_name_plural = 'Locations to Manager'
        permissions = (
            ("view_location_to_manager", "Can see Location to Manager"),
        )

    def get_location(self):
        return "\n".join([l.location for l in self.location.all()])

    def get_detailed_location(self):
        return "\n".join([l.detailed_location for l in self.location.all()])

    def __str__(self):
        return '%s %s' % (self.location, self.manager)


class WorkersToLocation(models.Model):
    location = models.ForeignKey(Location, null=True, on_delete=models.SET_NULL)
    workers = models.ManyToManyField(User)

    class Meta:
        app_label = 'hr_working_hours'
        verbose_name_plural = 'Workers to Location'
        permissions = (
            ("view_workers_to_location", "Can see Workers to Location"),
        )

    def __str__(self):
        return '%s %s' % (self.location, self.workers)


def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]


class ManagerToWorker(models.Model):
    manager = models.ForeignKey(User, related_name='manager', null=True, blank=True,
                                on_delete=models.SET(get_sentinel_user))
    worker = models.OneToOneField(User, related_name='worker', null=True, unique=True, on_delete=models.SET_NULL)

    class Meta:
        app_label = 'hr_working_hours'
        verbose_name_plural = 'Manager to Workers'
        permissions = (
            ("view_manager_to_worker", "Can see Manager to Worker"),
        )

    def __str__(self):
        return self.manager, self.worker


class LastDay(models.Model):
    worker = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)
    first_day = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True)
    last_day = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True)

    class Meta:
        app_label = 'hr_working_hours'
        verbose_name_plural = 'Last days of work'
        permissions = (
            ("view_last_days", "Can view last days"),
        )

    def __str__(self):
        return '%s %s %s' % (self.worker, self.first_day, self.last_day)

canteen/forms.py
# -*- coding: utf-8 -*-
from django import forms

from canteen.models import Product, Order, Menu, OrderItems, UserCompanyCard, Company, OrderConsents


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'


class UserCompanyCardForm(forms.ModelForm):
    class Meta:
        model = UserCompanyCard
        fields = '__all__'


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'


class ItemsForm(forms.ModelForm):
    class Meta:
        model = OrderItems
        fields = '__all__'


class SearchForm(forms.Form):
    card_id = forms.CharField(max_length=255)


class MyModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return '%s %s' % (obj.name, obj.discount)


class CreateUserForm(forms.Form):
    shortsign = forms.CharField(label='shortsign', max_length=50)
    company = forms.ModelChoiceField(queryset=Company.objects.all())
    card = forms.CharField(label='active card nr', max_length=255, required=False)
    temp_card_date = forms.DateField(label='active card valid until:', required=False)
    card_original = forms.CharField(label='primary card nr', max_length=250, required=False)
    pers_number = forms.CharField(label='personal nr', max_length=255, required=False)
    first_day = forms.DateField(label='first day at work', required=False)
    last_day = forms.DateField(label='last day at work', required=False)

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields['company'].queryset = Company.objects.all()

    def clean_card_original(self):
        return self.cleaned_data['card_original'] or None

    def clean_card(self):
        return self.cleaned_data['card'] or None


class ConsentForm(forms.ModelForm):
    class Meta:
        model = OrderConsents
        fields = ('answer',)

core/forms.py
from django import forms

from core.models import Sachnr, Disponent, Dispo


#Sachnr and Tabela Brakow
class SachnrForm(forms.ModelForm):
    class Meta:
        model = Sachnr
        fields = '__all__'


class DisponentForm(forms.ModelForm):
    class Meta:
        model = Disponent
        fields = '__all__'
        dispo = forms.ModelChoiceField(queryset=Dispo.objects.all())
        user = forms.ModelChoiceField(queryset=Disponent.objects.all())


class UploadFileForm(forms.Form):
    file = forms.FileField()


class DispoForm(forms.ModelForm):
    class Meta:
        model = Dispo
        fields = '__all__'

hr_working_hours/forms.py
from django import forms
from django.forms import ModelForm
from hr_working_hours.models import WorkingHours, LocationToManager, WorkersToLocation, LastDay, HolidayTypes
from django.contrib.auth.models import User
from django.db.models import Q


class WorkingHoursForm(ModelForm):
    class Meta:
        model = WorkingHours
        exclude = ['source_id', 'card', 'total_time', 'accepted_by']

    def __init__(self, *args, **kwargs):
        super(WorkingHoursForm, self).__init__(*args, **kwargs)
        self.fields['holiday_type'].queryset = HolidayTypes.objects.all()


class LocationToManagerForm(ModelForm):
    class Meta:
        model = LocationToManager
        fields = '__all__'


class WorkersToLocationForm(ModelForm):
    class Meta:
        model = WorkersToLocation
        fields = '__all__'


class LastDayForm(ModelForm):
    class Meta:
        model = LastDay
        fields = '__all__'


class ManagerToWorkerForm(forms.Form):
    manager = forms.ModelChoiceField(queryset=User.objects.filter(groups__name__icontains='managers'))


class ManagerToWorkersGroupForm(forms.Form):
    manager = forms.ModelChoiceField(queryset=User.objects.filter(groups__name__icontains='managers'))
    workers = forms.ModelMultipleChoiceField(queryset=User.objects.filter(
        ~Q(usercompanycard__company__name='apprentice')))

core/templates/users_addons/NewUserS1.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
    {% load hr_tables %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create User 1/3</title>
</head>
<!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script type="text/javascript" src="/static/js/selectize.js"></script>
<body>

<form action="{% url 'core:NewUserS1' %}" method="post" enctype="multipart/form-data" class="upload">
    {% csrf_token %}
    <div class="modal-dialog">
    <div class="modal-content">
                <div class="modal-header">
                    <h4>New user 1/3</h4>
                </div>
        <div class="modal-body" onchange="validateForm()">
            {{ form.as_p }}
        </div>
      <div class="modal-footer">
            <p>
                {% if form.shortsign %}
                <button id="submit_btn" class="btn btn-primary" type="submit">
                    <i class="fas fa-save"></i> save and proceed</button>
                {% endif %}
                <a href="{{ previous_page }}" type="button" class="btn btn-secondary">
                    <i class="fas fa-window-close"></i> cancel</a>

                <button class="btn btn-warning" type="reset">
                    <i class="fas fa-redo"></i> reset</button>

            </p>
                </div>
        </div>
    </div>
</form>
<script type="text/javascript">
        $(document).ready(function() {
                $("#id_manager, #id_company").selectize( {
                });
                var list = document.querySelectorAll("input[name='shortsign'], input[name='pers_number']");
                for (var i=0; i < list.length; i++) {
                    list[i].classList.add('form-control')
                }
            });
        var submitBtn = document.getElementById("submit_btn");
        var managerField = document.getElementById("id_manager");
        var companyField = document.getElementById("id_company");
        submitBtn.disabled=true;
        function validateForm() {
            submitBtn.disabled=true;
            var shortsign_field = document.getElementById("id_shortsign");
            if (shortsign_field.value.length!==0 & managerField.value.length!==0 & companyField.value.length!==0) {
                submitBtn.removeAttribute("disabled")
            }
                }
</script>
</body>
</html>
{% endblock %}

core/templates/users_addons/NewUserS2.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create User 2/3</title>
</head>
<!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script type="text/javascript" src="/static/js/selectize.js"></script>
<body>
<form action="{% url 'core:NewUserS2' shortsign=shortsign %}" method="post" enctype="multipart/form-data" class="upload">
    {% csrf_token %}
    <div class="modal-dialog">
    <div class="modal-content">
                <div class="modal-header">
                    <h4>New user 2/3</h4>
                    {{ kzz }} <h5>
                    <a href="{% url 'core:PrintCard' shortsign %}" type="button" class="btn btn-outline-info">
                        <i class="fas fa-credit-card"></i> print card
                    </a>
                    </h5>
                </div>
        <div class="modal-body">
            <label for="id_card">scan a card here:</label>
            {{ form.card_original }}
        </div>
      <div class="modal-footer">
            <p>
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-save"></i> save and proceed</button>

                <button class="btn btn-warning" type="reset">
                    <i class="fas fa-redo"></i> reset</button>

            </p>
                </div>
        </div>
    </div>
</form>
<script type="text/javascript">
        $(document).ready(function() {
                var list = document.querySelectorAll("input[name='card_original']");
                for (var i=0; i < list.length; i++) {
                    list[i].classList.add('form-control')
                }
                $("form").bind("keypress", function(e) {
            if (e.keyCode == 13) {
                return false;
            }
        });
            });
</script>
</body>
</html>
{% endblock %}

core/templates/users_addons/NewUserS3.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create User 3/3</title>
</head>
<!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>

<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script type="text/javascript" src="/static/js/selectize.js"></script>

<!-- datetimepicker CSS -->
<link rel="stylesheet" type="text/css" href="/static/css/jquery.datetimepicker.css">
<!-- datetimepicker JS -->
<script src="/static/js/jquery.datetimepicker.js"></script>
<body>

<form action="{% url 'core:NewUserS3' shortsign=shortsign %}" method="post" enctype="multipart/form-data" class="upload">
    {% csrf_token %}
    <div class="modal-dialog">
    <div class="modal-content">
                <div class="modal-header">
                    <h4>New user 3/3</h4>
                    <h5>{{ kzz }}</h5>
                </div>
        <div class="modal-body">
            <label for="id_worker">contract valid for:</label>
            {{ form.as_p }}
        </div>
      <div class="modal-footer">
            <p>
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-save"></i> save and proceed</button>

                <button class="btn btn-warning" type="reset">
                    <i class="fas fa-redo"></i> reset</button>

            </p>
                </div>
        </div>
    </div>
</form>
<script type="text/javascript">
        $(document).ready(function() {
                var list = document.querySelectorAll("select[name='worker']," +
                    " input[name=first_day], input[name=last_day]");
                for (var i=0; i < list.length; i++) {
                    list[i].classList.add('form-control')
                }
                document.getElementById("id_first_day").previousElementSibling.innerHTML = 'first day at work:';
                document.getElementById("id_last_day").previousElementSibling.innerHTML = 'last day at work:';
                $('#id_first_day, #id_last_day').datetimepicker({
                    format: 'd.m.Y',
                    lang: 'pl',
                    timepicker: false,
                    weeks: true,
                    dayOfWeekStart: 1
                });
                $("form").bind("keypress", function(e) {
            if (e.keyCode == 13) {
                return false;
            }
        });
            });
</script>
</body>
</html>
{% endblock %}

core/templates/users_addons/edit_pers_number.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit personal number</title>
</head>
<body>
<br/>
<div class="col-md-4 column">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
    <p>
        <label for="id_user">user:</label>
            <select id="id_user" name="user" class="users">
                <option value="{{ edit.user.id }}" selected>{{ edit.user.username }}</option>
        </select>
    </p>
    <p>
        <label for="id_pers_number">personal number:</label>
        <input id="id_pers_number" maxlength="150" name="pers_number" type="text" class="form-control" value="{{ edit.pers_number }}">
    </p>
        <p><input class="btn btn-success" type="submit" value="Save">
            {% if perms.users_addons.delete_personal_number %}
            <a type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_prompt">Delete</a>
            {% endif %}
    </p>
    </form>

    </div>

<!-- delete event -->
    <script>
        $('#delete_prompt').modal('show');
    </script>
  <!-- Trigger the modal with a button -->
  <div id="delete_prompt" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
          <b class="modal-title">Are you sure you want to delete this number?</b>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
    <div class="modal-footer">
        <a href="{% url 'core:delete_pers_number' edit.id %}" type="button"
                   class="btn btn-danger">yes, delete</a>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">no</button>
    </div>
        </div>
    </div>
  </div>
  </div>
</body>
</html>
{% endblock %}

core/templates/users_addons/pers_numbers.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Personal Numbers</title>
</head>
<link rel="stylesheet" type="text/css" href="/static/datables/datatables.min.css">
<script type="text/javascript" src="/static/js/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="/static/datables/datatables.js"></script>

<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script type="text/javascript" src="/static/js/selectize.js"></script>
<body>
<script type="text/javascript">
        $(document).ready(function() {
                $(".users").selectize( {
                });
            });
        $(document).ready(function() {
				$('#tabela').dataTable({

                });
			} );
		</script>
<br/>
<p><a href="{% url 'dashboard:dashboard' %}" type="button" class="btn btn-outline-primary">Dashboard</a></p>

<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="tabela">
	<thead>
		<tr>
			<th>Shortsign</th>
			<th>personal number</th>
        </tr>
	</thead>
	<tbody>
    {% for n in pers_numbers %}
		<tr>
            <td>{{ n.user.username }}
                <a href="{% url 'core:edit_pers_numbers' n.id %}"><i class="fa fa-edit"></i></a>
            </td>
            <td>{{ n.pers_number }}</td>
		</tr>
    {% endfor %}
</table>
<div class="col-md-4 column">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
    <p>
        <label for="id_user">user:</label>
            <select id="id_user" name="user" class="users">
                <option>---</option>
                {% for n in diff %}
                <option value="{{ n.id }}">{{ n.username }}</option>
                {% endfor %}
        </select>
    </p>
    <p>
        <label for="id_pers_number">personal number:</label>
        <input id="id_pers_number" maxlength="150" name="pers_number" type="text" class="form-control">
    </p>
        <p><input class="btn btn-success" type="submit" value="Save"></p>
    </form>

    </div>
</body>
</html>
{% endblock %}