canteen/urls.py
from django.urls import path

from . import views

app_name = 'canteen'
urlpatterns = [
   path('', views.menu_all, name='menu_all'),
   path('menu_all', views.menu_all, name='menu_all'),
   path('next_week_menu', views.next_week_menu, name='next_week_menu'),
   path('users_admin', views.users_admin, name='users_admin'),
   path('companies', views.companies, name='companies'),
   path('company_serialize', views.company_serialize, name='company_serialize'),
   path('orders_serialize', views.orders_serialize, name='orders_serialize'),
   path('company_edit/<int:pk>', views.company_edit, name='company_edit'),
   path('company_delete/<int:pk>', views.company_delete, name='company_delete'),
   path('users_company', views.users_company, name='users_company'),
   path('user_companies_edit/<int:pk>', views.user_companies_edit, name='user_companies_edit'),
   path('deactivate_user/<int:pk>', views.deactivate_user, name='deactivate_user'),
   path('activate_user/<int:pk>', views.activate_user, name='activate_user'),
   path('user_delete/<int:pk>', views.user_delete, name='user_delete'),
   path('menu_delete/<int:pk>', views.menu_delete, name='menu_delete'),
   path('dishes_all', views.dishes_all, name='dishes_all'),
   path('order/(<date>[0-9]{4}-[0-9]{2}-[0-9]{2})', views.order, name='order'),
   path('dishes_delete/<int:pk>', views.dishes_delete, name='dishes_delete'),
   path('dishes_edit/<int:pk>', views.dishes_edit, name='dishes_edit'),
   path('canteen_reports', views.reports, name='canteen_reports'),
   path('report_per_company/<from_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/<to_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/'
        '<int:company>', views.report_per_company, name='report_per_company'),
   path('report_from_to_csv/<from_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/<to_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/'
        '<int:company>', views.report_per_company_csv, name='report_from_to_csv'),
   path('report_per_person/<from_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/<to_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/'
        '<int:company>', views.report_per_person, name='report_per_person'),
   path('report_per_person_csv/<from_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/<to_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/'
        '<int:company>', views.report_per_person_csv, name='report_per_person_csv'),
   path('incomplete_orders/<from_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/<to_date>[0-9]{2}-[0-9]{2}-[0-9]{4}',
        views.incomplete_orders, name='incomplete_orders'),
   path('show_cancel_orders/<from_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/<to_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/'
        '<int:user_id>', views.show_cancel_orders, name='show_cancel_orders'),
   path('confirm_cancel_orders/<from_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/<to_date>[0-9]{2}-[0-9]{2}-[0-9]{4}/'
        '<int:user_id>', views.confirm_cancel_orders, name='confirm_cancel_orders'),
   path('orders_for_the_day/<day>[0-9]{2}-[0-9]{2}-[0-9]{4}', views.orders_for_the_day, name='orders_for_the_day'),
   path('orders_for_the_day_csv/<day>[0-9]{2}-[0-9]{2}-[0-9]{4}', views.orders_for_the_day_csv,
        name='orders_for_the_day_csv'),
   path('my_account', views.my_account, name='my_account'),
   path('diner_front', views.diner_front, name='diner_front'),
   path('how_many_left', views.how_many_left, name='how_many_left'),
   path('show_order/<int:card>', views.show_order, name='show_order'),
   path('close_order/<int:card>', views.close_order, name='close_order'),
   path('sold_unsold/<int:pk>', views.sold_unsold, name='sold_unsold'),
   path('change_quantity/<int:pk>/<operator>[\w-]+', views.change_quantity,
        name='change_quantity'),
   path('user_card_serialize', views.user_card_serialize, name='user_card_serialize'),
   path('get_card/<date>[0-9]{4}-[0-9]{2}-[0-9]{2}', views.get_card, name='get_card'),
   path('order_touch/<date>[0-9]{4}-[0-9]{2}-[0-9]{2}/<int:card>', views.order_touch, name='order_touch'),
   path('menu_touch', views.menu_touch, name='menu_touch'),
   path('touch_next_week', views.touch_next_week, name='touch_next_week'),
   path('touch_too_late', views.touch_too_late, name='touch_too_late')
]

core/urls.py
from django.urls import path

from . import views, views_managers_locations, views_users_addons

app_name = 'core'
urlpatterns = [
    path('', views.main, name='main'),
    path('main', views.main, name='main'),
    path('edit_sachnr/<str:sachnr>', views.edit_sachnr, name='edit_sachnr'),
    path('delete_sachnr/<int:pk>', views.delete_sachnr, name='delete_sachnr'),
    path('disponent_all/', views.disponent_all, name='disponent_all'),
    path('edit_disponent/<int:pk>', views.edit_disponent, name='edit_disponent'),
    path('delete_disponent/<int:pk>', views.delete_disponent, name='delete_disponent'),
    path('serialize_sachnr/', views.serialize_sachnr, name='serialize_sachnr'),
    path('sachnr_detailed_view/', views.sachnr_select_detailed_view, name='sachnr_select_detailed_view'),
    path('sachnr_details/<int:pk>', views.sachnr_details, name='sachnr_details'),
    path('import', views.import_data, name='import_data'),
    path('dispo_all', views.dispo_all, name='dispo_all'),
    path('dispo_delete/<int:pk>', views.dispo_delete, name='dispo_delete'),
    path('edit_dispo/<int:pk>', views.edit_dispo, name='edit_dispo'),
    path('serialize_deliverer/', views.serialize_deliverer, name='serialize_deleverer'),
    # managers_locations
    path('edit_responsible/<int:pk>', views_managers_locations.edit_responsible, name='edit_responsible'),
    path('responsible_all', views_managers_locations.responsible_all, name='responsible_all'),
    path('delete_responsible/<int:pk>', views_managers_locations.delete_responsible, name='delete_responsible'),
    path('location_all', views_managers_locations.location_all, name='location_all'),
    path('location_delete/<int:pk>', views_managers_locations.location_delete, name='location_delete'),
    path('edit_location/<int:pk>', views_managers_locations.edit_location, name='edit_location'),
    # users_addons
    path('pers_numbers', views_users_addons.pers_numbers, name='pers_numbers'),
    path('edit_pers_number/<int:pk>', views_users_addons.edit_pers_number, name='edit_pers_numbers'),
    path('delete_pers_number/<int:pk>', views_users_addons.delete_pers_number, name='delete_pers_number'),
    path('users_serialize', views_users_addons.users_serialize, name='users_serialize'),
    path('users_temp_serialize', views_users_addons.users_temp_serialize, name='users_temp_serialize'),
    path('NewUserS1', views_users_addons.NewUserS1, name='NewUserS1'),
    path('NewUserS2/<str:shortsign>', views_users_addons.NewUserS2, name='NewUserS2'),
    path('NewUserS3/<str:shortsign>', views_users_addons.NewUserS3, name='NewUserS3'),
    path('NewAccount/<str:shortsign>/<str:manager>', views_users_addons.NewAccount, name='NewAccount'),
    path('AddCompany/<str:shortsign>/<str:operator>', views_users_addons.AddCompany, name='AddCompany'),
    path('AddPersNumber/<str:shortsign>/<str:pers_number>', views_users_addons.AddPersNumber,
         name='AddPersNumber'),
    path('SaveCard/<str:shortsign>/<str:card>', views_users_addons.SaveCard, name='SaveCard'),
    path('PrintCard/<str:shortsign>', views_users_addons.PrintCard, name='PrintCard'),
    path(
        'SetLastDay/<str:shortsign>/<last_day>/<first_day>', views_users_addons.SetLastDay, name='SetLastDay'),
    # suppliers
    path('serialize_supplier', views.serialize_supplier, name='serialize_supplier'),
]

django3_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', dashboard_views.dashboard, name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('instructions/', include('instructions.urls')),
    path('canteen/', include('canteen.urls')),
    path('hr_working_hours/', include('hr_working_hours.urls')),
    path('hardware/', include('hardware.urls')),
    path('core/', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

canteen/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.admin import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from core.models_users_addons import Consent


class Company(models.Model):
    name = models.CharField(max_length=250, unique=True)
    discount = models.CharField(max_length=100, verbose_name='discount')

    def __str__(self):
        return '%s %s' % (self.name, self.discount)

    class Meta:
        verbose_name_plural = 'Companies'


class UserCompanyCard(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    card = models.CharField(max_length=250, blank=True, null=True)
    card_original = models.CharField(max_length=250, unique=True, blank=True, null=True)
    temp_card_date = models.DateField(default=None, blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, blank=True)

    def clean_card(self):
        return self.clean_fields('card_original') or None

    def __str__(self):
        return '%s %s %s %s %s' % (self.user, self.card, self.card_original, self.temp_card_date,
                                   self.company)


@receiver(post_save, sender=User)
def create_user_company_card(sender, instance, created, **kwargs):
    if created:
        UserCompanyCard.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_company_card(sender, instance, **kwargs):
    try:
        instance.usercompanycard.save()
    except:
        UserCompanyCard.objects.create(user_id=instance.id)


class Product(models.Model):
    name = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return '%s %s' % (self.name, self.price)

    class Meta:
        permissions = (
            ("draw_report", "can draw report"),
        )


class Menu(models.Model):
    date = models.DateField()
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return '%s' % self.product

    class Meta:
        permissions = (
            ("view_stolowka_menu", "can view menu"),
            ("diner_front", "access to diner front")
            )


class Order(models.Model):
    date = models.DateField()
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return '%s %s %s' % (self.date, self.user, self.complete)


class OrderItems(models.Model):
    order = models.ForeignKey(Order, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Menu, null=True, blank=True, on_delete=models.SET_NULL)
    quantity = models.IntegerField()
    sold = models.BooleanField(default=True)

    def __str__(self):
        return '%s %s %s %s' % (self.order, self.product_id, self.quantity, self.sold)

    class Meta:
        verbose_name_plural = 'OrderItems'


class OrderConsents(models.Model):
    order = models.ForeignKey(Order, null=True, blank=True, related_name='order', on_delete=models.SET_NULL)
    consent = models.ForeignKey(Consent, null=True, blank=True, on_delete=models.SET_NULL)
    answer = models.BooleanField(default=False)

    def __str__(self):
        return '%s %s' % (self.order, self.consent)

    class Meta:
        verbose_name_plural = 'OrderConsents'

canteen/forms.py
# -*- coding: utf-8 -*-
from django import forms

from canteen.models import Product, Order, Menu, OrderItems, UserCompanyCard, Company, OrderConsents


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'


class UserCompanyCardForm(forms.ModelForm):
    class Meta:
        model = UserCompanyCard
        fields = '__all__'


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'


class ItemsForm(forms.ModelForm):
    class Meta:
        model = OrderItems
        fields = '__all__'


class SearchForm(forms.Form):
    card_id = forms.CharField(max_length=255)


class MyModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return '%s %s' % (obj.name, obj.discount)


class CreateUserForm(forms.Form):
    shortsign = forms.CharField(label='shortsign', max_length=50)
    company = forms.ModelChoiceField(queryset=Company.objects.all())
    card = forms.CharField(label='active card nr', max_length=255, required=False)
    temp_card_date = forms.DateField(label='active card valid until:', required=False)
    card_original = forms.CharField(label='primary card nr', max_length=250, required=False)
    pers_number = forms.CharField(label='personal nr', max_length=255, required=False)
    first_day = forms.DateField(label='first day at work', required=False)
    last_day = forms.DateField(label='last day at work', required=False)

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields['company'].queryset = Company.objects.all()

    def clean_card_original(self):
        return self.cleaned_data['card_original'] or None

    def clean_card(self):
        return self.cleaned_data['card'] or None


class ConsentForm(forms.ModelForm):
    class Meta:
        model = OrderConsents
        fields = ('answer',)

canteen/templates/canteen/company_edit.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>change company name</title>
</head>
<body>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script type="text/javascript" src="/static/js/selectize.js"></script>
<script>
        $(document).ready(function() {
            $(".discount").selectize({});
        })
</script>
<form method="post" enctype="multipart/form-data">
    <div class="col-md-4 column">
    {% csrf_token %}
    <p> <label for="id_name">company name:</label>
            <input id="id_name" maxlength="250" name="name" type="text" class="form-control" value="{{ edit.name }}">
        </p>
        <p> <label for="id_discount">discount:</label>
            <select class="discount" id="id_discount" name="discount">
                    <option selected="selected" value={{ edit.discount }}>{{ edit.discount }}</option>
                        <option value="100%">100%</option>
                        <option value="60%">60%</option>
                        <option value="50%">50%</option>
                </select>
        </p>
        <button class="btn btn-primary" type="submit">Save</button>
        <a href="{% url 'canteen:companies' %}" type="button" class="btn btn-secondary">Cancel</a>
        <a href="{% url 'canteen:company_delete' edit.id %}" type="button" class="btn btn-danger">Delete</a>
    </div>
</form>
</body>
</html>
{% endblock %}

canteen/templates/canteen/edit_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit order</title>
    <link rel="stylesheet" type="text/css" href="/static/stolowka/css/dataTables.bootstrap.css">
<script type="text/javascript" language="javascript" src="/static/stolowka/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" language="javascript" src="/static/stolowka/js/dataTables.bootstrap.js"></script>

<!-- selectize CSS -->
<link rel="stylesheet" href="/static/stolowka/css/selectize.css"/>
<!--selectize JS -->
<script language="JavaScript" type="text/javascript" src="/static/stolowka/js/selectize.js"></script>

<!-- datetimepicker CSS -->
<link rel="stylesheet" type="text/css" href="/static/stolowka/css/jquery.datetimepicker.css">
<!-- datetimepicker JS -->
<script src="/static/stolowka/js/jquery.datetimepicker.js"></script>
<!-- dynamic-formset -->
<script src="/static/stolowka/js/dynamic-formset.js"></script>
</head>
<body>

{#<a href="{% url 'orders' %}" class="btn btn-primary" role="button">Orders</a>#}
{#<a href="{% url 'sides' %}" class="btn btn-primary" role="button">Sides</a>#}
{#<a href="{% url 'menu' %}" class="btn btn-primary" role="button">Menu</a>#}

{#<p>#}
{#{{ form.as_p }}#}
{#    {{ formset.as_p }}#}
{#</p>#}
{##}
{#{% for n in edit_dishes %}#}
{#<ul>{{ n.dish }}</ul>#}
{#{% if n.sides.values %}<li>{{ n.dish_id }}</li>{% endif %}#}
{#{% endfor %}#}


<form method="post" accept-charset="UTF-8" enctype="multipart/form-data" action="">
    {% csrf_token %}
    <label for="id_date">data:</label>
    <input id="id_date" name="date" type="text" value="{{ date }}">
        <label for="id_user">user:</label>
    <input id="id_user" name="user" type="text">
        <label for="id_price">cena razem:</label>
    <input id="id_price" name="price" type="text">

    {% for n in edit %}
        <p>
    <label for="dish">dish:</label>
        <input id="dish" name="'dish" type="text" value="{{ n.dish.name }}">
    <label for="sides">sides:</label>
        <select style="width: 300px" class="id_meal_set-0-sides" id="id_meal_set-0-sides" name="meal_set-0-sides" multiple="multiple">
                                <option value="{{ n.sides }}" selected="selected">{{ n.sides.name }}</option>
                        </select>
        <label for="quantity">ilość:</label>
        <input id="quantity" name="quantity" type="number" step="1" value="0">
        <label for="dish_price">cena:</label>
        <input id="dish_price" name="dish_price" value="{{ n.dish.price }}">
        </p>
    {% endfor %}

{#    {{ form.user }}#}
{#    {{ form.price }}#}
{#{{ formset.management_form }}#}
{#{% for item in edit_dishes %}#}
{#    {{ formset.management_form }}#}
{#    {% for form in formset %}#}
{#        {{ form.as_p }}#}
{#    {% endfor %}#}
{##}
{#{% endfor %}#}

{#{{ formset.management_form }}#}
{#    {% for form in formset %}#}
{#        {{ form.id }}#}
{#        <ul>#}
{#            <li>{{ form.dish }}</li>#}
{#            <li>{{ form.sides }}</li>#}
{#        </ul>#}
{#    {% endfor %}#}
{#{{ formset.as_p }}#}

    <button class="btn btn-default" type="submit">zapisz</button>
</form>

{{ a.values }}
</body>
</html>

canteen/templates/canteen/menu_edit.html
{% block content %}
    {% load l10n %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>edit dish</title>
</head>


<body>
<script type="text/javascript" charset="utf-8">

    $(document).ready(function() {
                $(".selectize").selectize({
                plugins: ['remove_button']

                });
            });

</script>

<form action="{% url 'menu_edit' edit.id %}" enctype="multipart/form-data" method="post" class="upload">

    {% csrf_token %}

    <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">edit dish</h4>
                <p>
                    <label for="id_name">name:</label>
                    <input id="id_name" maxlength="250" name="name" type="text" class="form-control" value="{{ edit.name }}">
                </p>
                <p>
                    <label for="id_sides">sides:</label>
                    <select class="selectize" multiple="multiple" id="id_sides" name="sides">
                        {% for n in edit_sides %}
                        <option value="{{ n.id }}" selected="selected">{{ n.name }}</option>
                        {% endfor %}
                        {% for n in sides %}
                        <option value="{{ n.id }}">{{ n.name }}</option>
                        {% endfor %}
                        </select>
                    </p>
                    <p>
                        <label for="id_price">price:</label>
                        <input id="id_price" class="form-control" name="price" step="0,01" value="{{ edit.price|unlocalize }}">
                    </p>
            <div class="modal-footer">
        <button class="btn btn-info" type="submit">save</button>
        <a href="{% url 'canteen:menu_all' %}" type="button" class="btn btn-default">cancel</a>
    </div>

      </div>
    </div>
  </div>

</form>

</body>
</html>
{% endblock %}

canteen/templates/canteen/menu_touch.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>
    <script src="/static/js/jquery-3.4.1.min.js"></script>
      <link href="/static/css/bootstrap.css" rel="stylesheet">
      <script src="/static/js/bootstrap.bundle.js"></script>
      <script defer src="/static/icons/all.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/datables/datatables.min.css">
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/datables/datatables.js"></script>
    <script>
        $(document).ready(function() {
            $('#menu_table').dataTable();
        })
    </script>

</head>
<body>
<br/>
<div class="container-fluid">
    {% if url == 'menu_touch' %}
        <a href="{% url 'canteen:touch_next_week' %}" class="btn btn-outline-primary action-button" role="button" style="vertical-align:top; float: right">next week</a>
    {% else %}
        <a href="{% url 'canteen:menu_touch' %}" class="btn btn-outline-primary action-button" role="button" style="vertical-align:top; float: right">current week</a>
    {% endif %}
    <h3>Menu from {{ start_week }} to {{ end_week }} </h3>
<div class="table-responsive">
<table class="table table-striped table-bordered">
<tbody>

<tr>
    <th>{{ monday|date:'D' }} {{ monday }}</th>
    <th>{{ tuesday|date:'D' }} {{ tuesday }}</th>
    <th>{{ wednesday|date:'D' }} {{ wednesday }}</th>
    <th>{{ thursday|date:'D' }} {{ thursday }}</th>
    <th>{{ friday|date:'D' }} {{ friday }}</th>
<tr>
    <td>{% if monday_menu %}
            {% for n in monday_menu %}
            <p>{{ n.product.name }} {{ n.product.sides.all }} {{ n.product.price }}</p>
            {% endfor %}
        {% endif %}
    </td>

    <td>{% if tuesday_menu %}
            {% for n in tuesday_menu %}
            <p>{{ n.product.name }} {{ n.product.sides.all }} {{ n.product.price }}</p>
            {% endfor %}
        {% endif %}
    </td>

    <td>{% if wednesday_menu %}
            {% for n in wednesday_menu %}
            <p>{{ n.product.name }} {{ n.product.sides.all }} {{ n.product.price }}</p>
            {% endfor %}
        {% endif %}
    </td>

    <td>{% if thursday_menu %}
            {% for n in thursday_menu %}
            <p>{{ n.product.name }} {{ n.product.sides.all }} {{ n.product.price }}</p>
            {% endfor %}
        {% endif %}
    </td>

    <td>{% if friday_menu %}
            {% for n in friday_menu %}
            <p>{{ n.product.name }} {{ n.product.sides.all }} {{ n.product.price }}</p>
            {% endfor %}
        {% endif %}
    </td>
</tr>
    <td>
        {% if monday_menu and monday|date:"Y-m-d 09:30" > order_time|date:"Y-m-d H:i" %}
            <a type="button" class="btn btn-outline-primary" href="{% url 'canteen:get_card' monday|date:"Y-m-d" %}?next={{ request.path|urlencode }}">
            <i class="fas fa-utensils"></i> place order</a>
        {% endif %}
    </td>
    <td>
        {% if tuesday_menu and tuesday|date:"Y-m-d 09:30" > order_time|date:"Y-m-d H:i" %}
            <a type="button" class="btn btn-outline-primary" href="{% url 'canteen:get_card' tuesday|date:"Y-m-d" %}?next={{ request.path|urlencode }}">
            <i class="fas fa-utensils"></i> place order</a>
        {% endif %}
    </td>
    <td>
        {% if wednesday_menu and wednesday|date:"Y-m-d 09:30" > order_time|date:"Y-m-d H:i" %}
            <a type="button" class="btn btn-outline-primary" href="{% url 'canteen:get_card' wednesday|date:"Y-m-d" %}?next={{ request.path|urlencode }}">
            <i class="fas fa-utensils"></i> place order</a>
        {% endif %}
    </td>
    <td>
        {% if thursday_menu and thursday|date:"Y-m-d 09:30" > order_time|date:"Y-m-d H:i" %}
            <a type="button" class="btn btn-outline-primary" href="{% url 'canteen:get_card' thursday|date:"Y-m-d" %}?next={{ request.path|urlencode }}">
            <i class="fas fa-utensils"></i> place order</a>
        {% endif %}
    </td>
    <td>
        {% if friday_menu and friday|date:"Y-m-d 09:30" > order_time|date:"Y-m-d H:i" %}
            <a type="button" class="btn btn-outline-primary" href="{% url 'canteen:get_card' friday|date:"Y-m-d" %}next={{ request.path|urlencode }}">
            <i class="fas fa-utensils"></i> place order</a>
        {% endif %}
    </td>
</tbody>
</table>

</div>
</div>
<style>
    th {
        width: 20%;
    }
    td {
        text-align: center;
    }
</style>
</body>
</html>
{% endblock %}

canteen/templates/canteen/too_late.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Too late</title>
</head>
<body>

<div style="text-align:center;">
    <h2>Too late!</h2>
    <h3>All of the orders for the current day can be cancelled befor 9.30 A.M.</h3>
    <h3><a href="{% url 'canteen:menu_all' %}" id="button" class="btn-lg btn-primary" role="button">OK</a></h3>
</div>

</body>
</html>
{% endblock %}

canteen/templates/canteen/users_admin.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hell's kitchen</title>
</head>
<body>
<br/>
<p>
<p>
    {% if perms.canteen.add_menu %}
    <a href="{% url 'canteen:menu_all' %}" class="btn btn-outline-primary" role="button">Menu</a>
    {% endif %}
</p>
<p>
    {% if perms.canteen.add_company %}
    <a href="{% url 'canteen:companies' %}" class="btn btn-primary" role="button">companies</a>
    {% endif %}
</p>
<p>
    {% if perms.canteen.add_product %}
    <a href="{% url 'canteen:dishes_all' %}" class="btn btn-primary" role="button">dishes</a>
    {% endif %}
</p>
<p>
    {% if perms.canteen.draw_report %}
    <a href="{% url 'canteen:canteen_reports' %}" class="btn btn-primary" role="button">reports</a>
    {% endif %}
</p>
</body>
</html>
{% endblock %}