core/urls.py
from django.urls import path

from . import views, views_managers_locations, views_users_addons

app_name = 'core'
urlpatterns = [
    path('', views.main, name='main'),
    path('main', views.main, name='main'),
    path('edit_sachnr/<str:sachnr>', views.edit_sachnr, name='edit_sachnr'),
    path('delete_sachnr/<int:pk>', views.delete_sachnr, name='delete_sachnr'),
    path('disponent_all/', views.disponent_all, name='disponent_all'),
    path('edit_disponent/<int:pk>', views.edit_disponent, name='edit_disponent'),
    path('delete_disponent/<int:pk>', views.delete_disponent, name='delete_disponent'),
    path('serialize_sachnr/', views.serialize_sachnr, name='serialize_sachnr'),
    path('sachnr_detailed_view/', views.sachnr_select_detailed_view, name='sachnr_select_detailed_view'),
    path('sachnr_details/<int:pk>', views.sachnr_details, name='sachnr_details'),
    path('import', views.import_data, name='import_data'),
    path('dispo_all', views.dispo_all, name='dispo_all'),
    path('dispo_delete/<int:pk>', views.dispo_delete, name='dispo_delete'),
    path('edit_dispo/<int:pk>', views.edit_dispo, name='edit_dispo'),
    path('serialize_deliverer/', views.serialize_deliverer, name='serialize_deleverer'),
    # managers_locations
    path('edit_responsible/<int:pk>', views_managers_locations.edit_responsible, name='edit_responsible'),
    path('responsible_all', views_managers_locations.responsible_all, name='responsible_all'),
    path('delete_responsible/<int:pk>', views_managers_locations.delete_responsible, name='delete_responsible'),
    path('location_all', views_managers_locations.location_all, name='location_all'),
    path('location_delete/<int:pk>', views_managers_locations.location_delete, name='location_delete'),
    path('edit_location/<int:pk>', views_managers_locations.edit_location, name='edit_location'),
    # users_addons
    path('pers_numbers', views_users_addons.pers_numbers, name='pers_numbers'),
    path('edit_pers_number/<int:pk>', views_users_addons.edit_pers_number, name='edit_pers_numbers'),
    path('delete_pers_number/<int:pk>', views_users_addons.delete_pers_number, name='delete_pers_number'),
    path('users_serialize', views_users_addons.users_serialize, name='users_serialize'),
    path('users_temp_serialize', views_users_addons.users_temp_serialize, name='users_temp_serialize'),
    path('NewUserS1', views_users_addons.NewUserS1, name='NewUserS1'),
    path('NewUserS2/<str:shortsign>', views_users_addons.NewUserS2, name='NewUserS2'),
    path('NewUserS3/<str:shortsign>', views_users_addons.NewUserS3, name='NewUserS3'),
    path('NewAccount/<str:shortsign>/<str:manager>', views_users_addons.NewAccount, name='NewAccount'),
    path('AddCompany/<str:shortsign>/<str:operator>', views_users_addons.AddCompany, name='AddCompany'),
    path('AddPersNumber/<str:shortsign>/<str:pers_number>', views_users_addons.AddPersNumber,
         name='AddPersNumber'),
    path('SaveCard/<str:shortsign>/<str:card>', views_users_addons.SaveCard, name='SaveCard'),
    path('PrintCard/<str:shortsign>', views_users_addons.PrintCard, name='PrintCard'),
    path(
        'SetLastDay/<str:shortsign>/<last_day>/<first_day>', views_users_addons.SetLastDay, name='SetLastDay'),
    # suppliers
    path('serialize_supplier', views.serialize_supplier, name='serialize_supplier'),
]

django3_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', dashboard_views.dashboard, name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('instructions/', include('instructions.urls')),
    path('canteen/', include('canteen.urls')),
    path('hr_working_hours/', include('hr_working_hours.urls')),
    path('hardware/', include('hardware.urls')),
    path('core/', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hardware/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'hardware'
urlpatterns = [
    path('', views.search_devices, name='search_devices'),
    path('add_device/', views.add_device, name='add_device'),
    path('edit_device/<int:pk>', views.edit_device, name='edit_device'),
    path('delete_device/<int:pk>', views.delete_device, name='delete_device'),
    path('assign_device_modal/<int:device_id>', views.assign_device_modal,
        name='assign_device_modal'),

    path('categories_all', views.categories_all, name='categories_all'),
    path('add_category_modal', views.add_category_modal,
        name='add_category_modal'),
    path('edit_category_modal/<int:category_id>', views.edit_category_modal,
        name='edit_category_modal'),
    path('delete_category/<int:category_id>', views.delete_category,
        name='delete_category'),

    path('events_all', views.events_all, name='events_all'),
    path('add_event_modal', views.add_event_modal,
        name='add_event_modal'),
    path('edit_event_modal/<int:event_id>', views.edit_event_modal,
        name='edit_event_modal'),
    path('delete_event/<int:event_id>', views.delete_event,
        name='delete_event'),

    path('new_owner/<int:usercard>', views.new_owner, name='new_owner'),
    path('new_user_card', views.new_user_card, name='new_user_card')
]

hardware/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from datetime import datetime


def deleted_user():
    get_user_model().objects.get_or_create(username='deleted')[0]

def user_folder(instance, filename):
    if instance.owner:
        return 'hardware/{0}/{1}'.format(instance.owner.kzz.username, filename)
    else:
        return 'hardware/{0}/{1}'.format('IT', filename)

def managers_only():
        return {'groups__name': 'managers'}

def set_mac_address(instance):
    if len(instance) == 12 and ":" not in instance:
        address = ':'.join(instance[i:i+2] for i in range(0,len(instance),2))
    else:
        address = instance
    return '{0}'.format(address)


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"
        app_label = "hardware"


class Department(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        app_label = "hardware"


class Events(models.Model):
    action = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.action

    class Meta:
        verbose_name_plural = "Events"
        app_label = "hardware"


class Owner(models.Model):
    kzz = models.ForeignKey(User, related_name='kzz', blank=True, on_delete=models.SET(deleted_user))
    department = models.ForeignKey(Department, blank=True, null=True, on_delete=models.SET_NULL)
    supervisor = models.ForeignKey(
        User, related_name='supervisor', blank=True, null=True,
        on_delete=models.SET(deleted_user), limit_choices_to=managers_only
        )

    def __str__(self):
        return self.kzz.username

    class Meta:
        app_label = "hardware"


class Device(models.Model):
    """
    Contains basic data of a device.
    Draws category data from :model:`hardware.History`
    """
    description = models.CharField(max_length=255, blank=False)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    hostname = models.CharField(max_length=255, blank=True, unique=True)
    serial_number = models.CharField(max_length=255, blank=True)
    mac_address = models.CharField(max_length=100, blank=True)

    def save(self, *args, **kwargs):
        if self.mac_address:
            self.mac_address = set_mac_address(self.mac_address)
        super().save(*args, **kwargs)

    def __str__(self):
        return '%s %s %s %s' % (self.description, self.category, self.hostname,
        self.serial_number)

    class Meta:
        app_label = "hardware"
        unique_together = ['hostname', 'description']


class History(models.Model):
    """
    Describes current state of a device, draws data from :model:`hardware.Device`,
    :model:`hardware.Event` and :model:`hardware.Owner`.
    """
    device = models.ForeignKey(Device, null=True, on_delete=models.SET_NULL)
    assigned = models.DateField(auto_now_add=True, blank=True, null=True)
    decomissioned = models.DateField(auto_now=True, blank=True, null=True)
    event = models.ForeignKey(Events, null=True, on_delete=models.SET_NULL)
    uploaded = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    attachment = models.FileField(upload_to=user_folder, blank=True, null=True)
    owner = models.ForeignKey(Owner, max_length=255, null=True, blank=True, on_delete=models.SET_NULL)

    def save(self, *args, **kwargs):
        if self.attachment:
            self.uploaded = datetime.utcnow()
        super().save(*args, **kwargs)

    def __str__(self):
        return '%s %s %s %s' % (self.device, self.assigned, self.event, self.owner)

    class Meta:
        app_label = "hardware"
        verbose_name_plural = "History"

hardware/forms.py
from django import forms
from django.db.models.base import Model
from django.forms import Form, ModelForm, inlineformset_factory

from .models import (Category,
                    Department,
                    Events,
                    Owner,
                    Device,
                    History)


class EventForm(ModelForm):
    class Meta:
        model = Events
        fields = '__all__'


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class DeviceForm(ModelForm):
    class Meta:
        model = Device
        fields = '__all__'


class OwnerForm(ModelForm):
    class Meta:
        model = Owner
        fields = '__all__'


DeviceFormSet = inlineformset_factory(Device, History, extra=1, fields='__all__', can_delete=True)

class SearchForm(Form):
    actions = (
        [("","")] +
        list(Events.objects.all().values_list('action', 'action'))
        )
    categories = (
        [("","")] +
        list(Category.objects.all().values_list('name', 'name'))
    )

    description = forms.CharField(required=False, label='description')
    category = forms.ChoiceField(required=False, label='category', choices=categories)
    hostname = forms.CharField(required=False, label='hostname')
    serial_number = forms.CharField(required=False, label='serial number')
    mac_address = forms.CharField(required=False, label='MAC address')
    event = forms.ChoiceField(required=False, label='event', choices=actions)
    owner = forms.CharField(required=False, label='owner')


class AssignOwnerForm(Form):
    devices = (
        [("","")] +
        list(Device.objects.all().values_list('id', 'hostname'))
    )

    card = forms.CharField(label='card')
    device = forms.ChoiceField(label='device', choices=devices)


class NewCardForm(Form):
    card = forms.CharField(label='scan card here:')
    user = forms.CharField(label="user's shortsign")

hardware/templates/assign_device_modal.html
{% load static %}
{% block content %}
<html>
 <!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script language="JavaScript" type="text/javascript" src="/static/js/selectize.js"></script>
<head>
    <meta charset="UTF-8">
    <title>Assign the device</title>
</head>

<body>
<form enctype="multipart/form-data" method=POST action="{% url 'hardware:assign_device_modal' device_id=device %}" class="upload">
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Assign the device</h5>
                </div>
                <div class="modal-body" style="margin: 10px;">
                    {% csrf_token %}
                    {{form.as_p}}
                </div>
                <div class="modal-footer">
                    <button type="submit">Save</button>
                </div>
            </div>
    </div>
</form>
</body>
{% endblock %}

hardware/templates/categories_all.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="/static/datables/datatables.min.css">
		<script type="text/javascript" language="javascript" src="/static/js/bootstrap.js.map"></script>
		<script type="text/javascript" language="javascript" src="/static/datables/datatables.min.js"></script>
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#categories').dataTable();
			} );
		</script>
		<script>
        $(document).ready(function() {
            $('body').on('click', '[data-toggle="modal"]', function () {
                $($(this).data("target") + ' .modal-dialog').load($(this).data("remote"));
            });
        });
    </script>
		{% comment %} <!-- jQuery -->
		<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script> {% endcomment %}
		<!-- selectize CSS -->
		<link rel="stylesheet" href="/static/css/selectize.css"/>
		<!--selectize JS -->
		<script type="text/javascript" src="/static/js/selectize.js"></script>
</head>
<body>
<div style="margin: 9px">
	<a href="{% url 'hardware:search_devices' %}" type="button" class="btn btn-primary">Devices</a>
	{% comment %} <a href="{% url 'hardware:categories_all' %}" type="button" class="btn btn-primary">Categories</a> {% endcomment %}
</div>
<table cellpadding="0" cellspacing="0" border="0"
	class="table table-striped table-bordered table-hovered" id="categories">
	<thead>
		<tr>
			<th>name</th>
			<th>edit</th>
		</tr>
	</thead>
	<tbody>
	{% for n in categories %}
		<tr>
			<td>{{n.name}}</td>
			<td>
				<a data-remote="{% url 'hardware:edit_category_modal' category_id=n.id %}"
					data-toggle="modal", data-target="#edit_category_modal">
				<span class="fa fa-edit"></span>
			</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
<div id="edit_category_modal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        </div>
    </div>
</body>
</html>
{% endblock %}

hardware/templates/category_modal.html
{% load static %}
{% block content %}
<html>
 <!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script language="JavaScript" type="text/javascript" src="/static/js/selectize.js"></script>
<head>
    <meta charset="UTF-8">
    <title>Edit a category</title>
</head>

<body>
{% if category_id %}
<form enctype="multipart/form-data" method=POST action="{% url 'hardware:edit_category_modal' category_id=category_id %}" class="upload">
{% else %}
<form enctype="multipart/form-data" method=POST action="{% url 'hardware:add_category_modal' %}" class="upload">
{% endif %}
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit a category</h5>
                </div>
                <div class="modal-body" style="margin: 10px;">
                    {% csrf_token %}
                    {{form.as_p}}
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Save</button>
                    {% if category_id %}
                    <a href="{% url 'hardware:delete_category' category_id=category_id %}"
                     type="button" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a>
                    {% endif %}
                    <button type="button" class="btn btn-dark" data-dismiss="modal">
                        <i class="far fa-window-close"></i> Cancel</button>
                </div>
            </div>
    </div>
</form>
</body>
{% endblock %}

hardware/templates/device.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="/static/datables/datatables.min.css">
		<script type="text/javascript" language="javascript" src="/static/js/bootstrap.js.map"></script>
		<script type="text/javascript" language="javascript" src="/static/datables/datatables.min.js"></script>
		<!-- selectize CSS -->
		<link rel="stylesheet" href="/static/css/selectize.css"/>
		<!--selectize JS -->
		<script type="text/javascript" src="/static/js/selectize.js"></script>
		<script>
        $(document).ready(function() {
            $('body').on('click', '[data-toggle="modal"]', function () {
                $($(this).data("target") + ' .modal-dialog').load($(this).data("remote"));
            });
        });
    </script>
</head>
<body>
{% if device %}
<a data-remote="{% url 'hardware:assign_device_modal' device_id=device.id %}" class="btn btn-info" type="button" style="vertical-align:top; float: left"
       data-toggle="modal" data-target="#assign_device_modal">assign this device</a>
{% endif %}
<div class="col-sm-5">
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		{{formset.as_p}}
		<button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
		{% if device %}
		<a href="{% url 'hardware:delete_device' device.id %}" type="button" class="btn btn-danger"><i class="fas fa-trash"></i> Delete</a>
		{% endif %}
		<a href="{% url 'hardware:search_devices' %}" type="button" class="btn btn-dark"><i class="far fa-window-close"></i> Cancel</a>
	</form>
</div>
<div id="assign_device_modal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        </div>
    </div>

<script type="text/javascript">
        $(document).ready(function() {
			var dropdowns = document.querySelectorAll('select')
			console.log(dropdowns)
			$("#id_category, #id_event").selectize( {
                });
                var list = document.querySelectorAll("input");
                for (var i=0; i < list.length; i++) {
                    list[i].classList.add('form-control')
                }
            });
</script>
</body>
</html>
{% endblock %}

hardware/templates/edit_category_modal.html
{% load static %}
{% block content %}
<html>
 <!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script language="JavaScript" type="text/javascript" src="/static/js/selectize.js"></script>
<head>
    <meta charset="UTF-8">
    <title>Edit a category</title>
</head>

<body>
<form enctype="multipart/form-data" method=POST action="{% url 'hardware:edit_category_modal' category_id=category_id %}" class="upload">
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit a category</h5>
                </div>
                <div class="modal-body" style="margin: 10px;">
                    {% csrf_token %}
                    {{form.as_p}}
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" type="submit">Save</button>
                    <a href="{% url 'hardware:delete_category' category_id=category_id %}"
                     type="button" class="btn btn-danger">Delete</a>
                </div>
            </div>
    </div>
</form>
</body>
{% endblock %}

hardware/templates/event_modal.html
{% load static %}
{% block content %}
<html>
 <!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script language="JavaScript" type="text/javascript" src="/static/js/selectize.js"></script>
<head>
    <meta charset="UTF-8">
    <title>Edit an event</title>
</head>

<body>
{% if event_id %}
<form enctype="multipart/form-data" method=POST action="{% url 'hardware:edit_event_modal' event_id=event_id %}" class="upload">
{% else %}
<form enctype="multipart/form-data" method=POST action="{% url 'hardware:add_event_modal' %}" class="upload">
{% endif %}
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit an event</h5>
                </div>
                <div class="modal-body" style="margin: 10px;">
                    {% csrf_token %}
                    {{form.as_p}}
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Save</button>
                    {% if event_id %}
                    <a href="{% url 'hardware:delete_event' event_id=event_id %}"
                     type="button" class="btn btn-danger">
                     <i class="fas fa-trash"></i> Delete</a>
                    {% endif %}
                    <button type="button" class="btn btn-dark" data-dismiss="modal">
                        <i class="far fa-window-close"></i> Cancel</button>
                </div>
            </div>
    </div>
</form>
</body>
{% endblock %}

hardware/templates/events_all.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="/static/datables/datatables.min.css">
		<script type="text/javascript" language="javascript" src="/static/js/bootstrap.js.map"></script>
		<script type="text/javascript" language="javascript" src="/static/datables/datatables.min.js"></script>
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#events').dataTable();
			} );
		</script>
		<script>
        $(document).ready(function() {
            $('body').on('click', '[data-toggle="modal"]', function () {
                $($(this).data("target") + ' .modal-dialog').load($(this).data("remote"));
            });
        });
    </script>
		{% comment %} <!-- jQuery -->
		<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script> {% endcomment %}
		<!-- selectize CSS -->
		<link rel="stylesheet" href="/static/css/selectize.css"/>
		<!--selectize JS -->
		<script type="text/javascript" src="/static/js/selectize.js"></script>
</head>
<body>
<div style="margin: 9px">
	<a href="{% url 'hardware:search_devices' %}" type="button" class="btn btn-primary">
        <i class="fas fa-server"></i> Devices</a>
	<a data-remote="{% url 'hardware:add_event_modal' %}"
		data-toggle="modal", data-target="#edit_event_modal" type="button"
		class="btn btn-primary"><i class="fas fa-plus"></i> New event</a>
</div>
<table cellpadding="0" cellspacing="0" border="0"
	class="table table-striped table-bordered table-hovered" id="events">
	<thead>
		<tr>
			<th>action</th>
			<th>edit</th>
		</tr>
	</thead>
	<tbody>
	{% for n in events %}
		<tr>
			<td>{{n.action}}</td>
			<td>
				<a data-remote="{% url 'hardware:edit_event_modal' event_id=n.id %}"
					data-toggle="modal", data-target="#edit_event_modal">
				<span class="fa fa-edit"></span>
			</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
<div id="edit_event_modal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        </div>
    </div>
</body>
</html>
{% endblock %}

hardware/templates/list_devices.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="/static/datables/datatables.min.css">
		<script type="text/javascript" language="javascript" src="/static/js/bootstrap.js.map"></script>
		<script type="text/javascript" language="javascript" src="/static/datables/datatables.min.js"></script>
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#devices').dataTable();
			} );
		</script>
		{% comment %} <!-- jQuery -->
		<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script> {% endcomment %}
		<!-- selectize CSS -->
		<link rel="stylesheet" href="/static/css/selectize.css"/>
		<!--selectize JS -->
		<script type="text/javascript" src="/static/js/selectize.js"></script>
</head>
<body>
<div style="margin: 9px">
<a href="{% url 'hardware:add_device' %}" type="button" class="btn btn-primary"><i class="fas fa-server"></i> New Device</a>
<a href="{% url 'hardware:categories_all' %}" type="button" class="btn btn-primary"><i class="fas fa-shapes"></i> Categories</a>
<a href="{% url 'hardware:events_all' %}" type="button" class="btn btn-primary"><i class="fas fa-book"></i> Events</a>
</div>
<div class="col-sm-5">
<form style="margin: 9px" method=POST action="{% url 'hardware:search_devices' %}">
{% csrf_token %}
{{searchForm.as_p}}
<button class="btn btn-outline-secondary" type="submit"><i class="fas fa-search"></i> Search</button>

</form>
</div>
{% if searched %}
		<h5 style="margin: 9px">Results for:
			<ul class="list-inline">
			{% for v in searched.values %}
				{% if v %}
					<li class="list-inline-item">{{v}}</li>
				{% endif %}
			{%endfor%}
			</ul>
		</h5>
		<br/>
<table cellpadding="0" cellspacing="0" border="0"
	class="table table-striped table-bordered table-hovered" id="devices">
	<thead>
		<tr>
			<th>hostname</th>
			<th>description</th>
			<th>user</th>
			<th>category</th>
			<th>status</th>
		</tr>
	</thead>
	<tbody>
	{% for n in query %}
		<tr>
			<td><a href="{% url 'hardware:edit_device' pk=n.id %}">
                    <span class="fa fa-edit"></span>
                </a>{{n.hostname}}</td>
			<td>{{n.description}}</td>
			<td>{{n.history_set.last.owner|default_if_none:""}}</td>
			<td>{{n.category}}</td>
			<td>{{ n.history_set.last.event }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% else %}
		<h5>Search for your devices</h5>
{% endif %}

<script type="text/javascript">
        $(document).ready(function() {
                $("#id_category, #id_event").selectize( {
                });
                var list = document.querySelectorAll("input");
                for (var i=0; i < list.length; i++) {
                    list[i].classList.add('form-control')
                }
            });
</script>
</body>
</html>
{% endblock %}

hardware/templates/new_user_card.html
{% load static %}
{% block content %}
<html>
 <!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script language="JavaScript" type="text/javascript" src="/static/js/selectize.js"></script>
<head>
    <meta charset="UTF-8">
    <title>Assign the device</title>
</head>

<body>
<form enctype="multipart/form-data" method=POST action="{% url 'hardware:new_user_card' %}" class="upload">
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create a new user</h5>
                </div>
                <div class="modal-body" style="margin: 10px;">
                    {% csrf_token %}
                    {{form.as_p}}
                </div>
                <div class="modal-footer">
                    <button type="submit">Save</button>
                </div>
            </div>
    </div>
</form>
</body>
</html>
{% endblock %}