core/urls.py
from django.urls import path

from . import views, views_managers_locations, views_users_addons

app_name = 'core'
urlpatterns = [
    path('', views.main, name='main'),
    path('main', views.main, name='main'),
    path('edit_sachnr/<str:sachnr>', views.edit_sachnr, name='edit_sachnr'),
    path('delete_sachnr/<int:pk>', views.delete_sachnr, name='delete_sachnr'),
    path('disponent_all/', views.disponent_all, name='disponent_all'),
    path('edit_disponent/<int:pk>', views.edit_disponent, name='edit_disponent'),
    path('delete_disponent/<int:pk>', views.delete_disponent, name='delete_disponent'),
    path('serialize_sachnr/', views.serialize_sachnr, name='serialize_sachnr'),
    path('sachnr_detailed_view/', views.sachnr_select_detailed_view, name='sachnr_select_detailed_view'),
    path('sachnr_details/<int:pk>', views.sachnr_details, name='sachnr_details'),
    path('import', views.import_data, name='import_data'),
    path('dispo_all', views.dispo_all, name='dispo_all'),
    path('dispo_delete/<int:pk>', views.dispo_delete, name='dispo_delete'),
    path('edit_dispo/<int:pk>', views.edit_dispo, name='edit_dispo'),
    path('serialize_deliverer/', views.serialize_deliverer, name='serialize_deleverer'),
    # managers_locations
    path('edit_responsible/<int:pk>', views_managers_locations.edit_responsible, name='edit_responsible'),
    path('responsible_all', views_managers_locations.responsible_all, name='responsible_all'),
    path('delete_responsible/<int:pk>', views_managers_locations.delete_responsible, name='delete_responsible'),
    path('location_all', views_managers_locations.location_all, name='location_all'),
    path('location_delete/<int:pk>', views_managers_locations.location_delete, name='location_delete'),
    path('edit_location/<int:pk>', views_managers_locations.edit_location, name='edit_location'),
    # users_addons
    path('pers_numbers', views_users_addons.pers_numbers, name='pers_numbers'),
    path('edit_pers_number/<int:pk>', views_users_addons.edit_pers_number, name='edit_pers_numbers'),
    path('delete_pers_number/<int:pk>', views_users_addons.delete_pers_number, name='delete_pers_number'),
    path('users_serialize', views_users_addons.users_serialize, name='users_serialize'),
    path('users_temp_serialize', views_users_addons.users_temp_serialize, name='users_temp_serialize'),
    path('NewUserS1', views_users_addons.NewUserS1, name='NewUserS1'),
    path('NewUserS2/<str:shortsign>', views_users_addons.NewUserS2, name='NewUserS2'),
    path('NewUserS3/<str:shortsign>', views_users_addons.NewUserS3, name='NewUserS3'),
    path('NewAccount/<str:shortsign>/<str:manager>', views_users_addons.NewAccount, name='NewAccount'),
    path('AddCompany/<str:shortsign>/<str:operator>', views_users_addons.AddCompany, name='AddCompany'),
    path('AddPersNumber/<str:shortsign>/<str:pers_number>', views_users_addons.AddPersNumber,
         name='AddPersNumber'),
    path('SaveCard/<str:shortsign>/<str:card>', views_users_addons.SaveCard, name='SaveCard'),
    path('PrintCard/<str:shortsign>', views_users_addons.PrintCard, name='PrintCard'),
    path(
        'SetLastDay/<str:shortsign>/<last_day>/<first_day>', views_users_addons.SetLastDay, name='SetLastDay'),
    # suppliers
    path('serialize_supplier', views.serialize_supplier, name='serialize_supplier'),
]

django3_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', dashboard_views.dashboard, name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('instructions/', include('instructions.urls')),
    path('canteen/', include('canteen.urls')),
    path('hr_working_hours/', include('hr_working_hours.urls')),
    path('hardware/', include('hardware.urls')),
    path('core/', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]


# sachnr & tabela brakow
class Dispo(models.Model):
    name = models.CharField(max_length=25)
    ekg = models.CharField(max_length=25, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'dispo'
        app_label = 'core'

    def __str__(self):
        return self.name, self.ekg


class Disponent(models.Model):
    dispo = models.ManyToManyField(Dispo)
    shortsign = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))

    class Meta:
        verbose_name_plural = 'responsible'
        app_label = 'core'

    def __str__(self):
        return '%s %s' % (self.dispo, self.shortsign)


class Sachnr(models.Model):
    sachnr = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=200)
    dispo = models.ForeignKey(Dispo, null=True, on_delete=models.SET(get_sentinel_user))
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Sachnummer'
        permissions = (
            ("view_core", "Can see app"),
            ("can_search_for_sachnr", "Can search for sachnr")
        )
        app_label = 'core'

    def __str__(self):
        return self.sachnr, self.description, (self.dispo.name, self.dispo.ekg)


class Deliverer(models.Model):
    number = models.CharField(max_length=150, blank=False)
    name = models.CharField(max_length=250, blank=False)

    class Meta:
        verbose_name_plural = 'deliverers'
        permissions = (
            ("view_core", "Can see app"),
        )
        app_label = 'core'

    def __str__(self):
        return self.number, self.name


class Supplier(models.Model):
    name = models.CharField(max_length=250, blank=False)

    class Meta:
        verbose_name_plural = 'Suppliers'
        app_label = 'core'

    def __str__(self):
        return '%s' % self.name


class Location(models.Model):
    location = models.CharField(max_length=150)
    detailed_location = models.CharField(max_length=250, null=True)

    class Meta:
        verbose_name_plural = 'core_location'
        app_label = 'core'
        permissions = (
            ("edit_location", "Can edit location"),
        )

    def __str__(self):
        return '%s %s' % (self.location, self.detailed_location)

core/forms.py
from django import forms

from core.models import Sachnr, Disponent, Dispo


#Sachnr and Tabela Brakow
class SachnrForm(forms.ModelForm):
    class Meta:
        model = Sachnr
        fields = '__all__'


class DisponentForm(forms.ModelForm):
    class Meta:
        model = Disponent
        fields = '__all__'
        dispo = forms.ModelChoiceField(queryset=Dispo.objects.all())
        user = forms.ModelChoiceField(queryset=Disponent.objects.all())


class UploadFileForm(forms.Form):
    file = forms.FileField()


class DispoForm(forms.ModelForm):
    class Meta:
        model = Dispo
        fields = '__all__'

core/views.py
import json
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.forms.models import modelformset_factory
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import HttpResponseRedirect, reverse
from django.db.models import Q
from django.template import loader

from core.forms import SachnrForm, DisponentForm, UploadFileForm, DispoForm
from core.models import Sachnr, Disponent, Dispo, Deliverer, Supplier


@login_required()
def main(request):
    if request.user.username == 'admin':
        dispo = Dispo.objects.all()
    elif request.user.groups.filter(name__contains='magazyn'):
        find_logistyka = Group.objects.get(name='logistyka').id
        dispo = Dispo.objects.filter(Q(disponent__shortsign__groups=find_logistyka))
    else:
        user_group = request.user.groups.all().values('id')
        dispo = Dispo.objects.filter(Q(disponent__shortsign__groups=user_group))
    if request.method == 'GET':
        form = SachnrForm()
    elif request.method == 'POST':
        form = SachnrForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            form = SachnrForm()
    template = loader.get_template('sachnr/show_all.html')
    return HttpResponse(template.render({'form': form, 'dispo': dispo}, request))


@permission_required('core.add_sachnr')
def sachnr_select_detailed_view(request):
    template = loader.get_template('sachnr/sachnr_detailed_view.html')
    return HttpResponse(template.render({}, request))


@permission_required('core.add_sachnr')
def sachnr_details(request, pk):
    sachnr_details = Sachnr.objects.filter(sachnr=pk)
    template = loader.get_template('sachnr/sachnr_details.html')
    context = {'sachnr_details': sachnr_details}
    return HttpResponse(template.render(context, request))


@permission_required('core.add_sachnr')
def edit_sachnr(request, sachnr):
    edit = Sachnr.objects.get(sachnr=sachnr)
    sachnr_disponent = Disponent.objects.filter(dispo=edit.dispo_id)
    dispo = Dispo.objects.all()
    template = loader.get_template('sachnr/edit.html')
    if request.method == 'POST':
        form = SachnrForm(request.POST, instance=edit)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:sachnr_select_detailed_view'))
    else:
        form = SachnrForm(instance=edit)

        return HttpResponse(template.render({'form': form, 'edit': edit, 'dispo': dispo,
                                             'sachnr_disponent': sachnr_disponent}, request))


@permission_required('core.add_sachnr')
def delete_sachnr(request, pk):
    delete = Sachnr.objects.get(id=pk).delete()
    if request.method == 'POST':
        form = SachnrForm(request.POST, instance=delete)
        form.u.delete()
        form.save()
    return HttpResponseRedirect(reverse('core:sachnr_select_detailed_view'))


@permission_required('core.can_search_for_sachnr')
def serialize_sachnr(request):
    all_sachnr = Sachnr.objects.values('id', 'sachnr', 'description')
    json_serializer = json.dumps(list(all_sachnr))
    return HttpResponse(json_serializer, content_type='application/json')


@permission_required('core.add_sachnr')
def import_data(request):
    template = loader.get_template('sachnr/import.html')
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            request.FILES['file'].save_to_database(
                model=Sachnr,
                mapdict=['sachnr', 'description', 'dispo_id'])

            return HttpResponse("OK")
        else:
            return HttpResponseBadRequest("error :(")
    else:
        form = UploadFileForm()
        return HttpResponse(template.render({'form': form}, request))


# DISPONENT #
@permission_required('core.add_disponent')
def disponent_all(request):
    find_logistyka = Group.objects.get(name='logistyka').id
    users = User.objects.filter(groups=find_logistyka)
    print(users)
    dispo_users = Disponent.objects.all()
    dispo = Dispo.objects.all()
    diff = []
    template = loader.get_template('sachnr/disponent_all.html')
    for all in users:
        found = False
        for sub in dispo_users:
            if sub.shortsign_id == all.id:
                found = True
                break
        if not found:
            diff.append(all)
    if request.method == 'POST':
        form = DisponentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:disponent_all'))
    else:
        form = DisponentForm()
    return HttpResponse(template.render({'all': dispo_users, 'form': form, 'users': diff,
                                         'dispo': dispo}, request))


@permission_required('core.add_disponent')
def delete_disponent(request, pk):
    delete = Disponent.objects.get(id=pk).delete()
    if request.method == 'POST':
        form = SachnrForm(request.POST, instance=delete)
        form.u.delete()
        form.save()
    return HttpResponseRedirect(reverse('core:disponent_all'))


@permission_required('core.add_disponent')
def edit_disponent(request, pk):
    edit = Disponent.objects.filter(id=pk)
    dispo_selected = Dispo.objects.filter(disponent__id=pk)
    dispo_all = Dispo.objects.all()
    disponent_sachnr = Sachnr.objects.filter(dispo__disponent=pk)
    EditFormSet = modelformset_factory(Disponent, fields=('dispo',), max_num=1, min_num=0)
    template = loader.get_template('sachnr/edit_disponent.html')
    if request.method == 'POST':
        formset = EditFormSet(request.POST, queryset=Disponent.objects.filter(id=pk))
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect(reverse('core:disponent_all'))
    else:
        formset = EditFormSet(queryset=Disponent.objects.filter(id=pk))

    return HttpResponse(template.render({'id': pk, 'form': formset, 'edit': edit,
                                         'dispo_selected': dispo_selected, 'dispo_all': dispo_all,
                                         'disponent_sachnr': disponent_sachnr}, request))

# DISPO #
@permission_required('core.add_dispo')
def dispo_all(request):
    dispo_all = Dispo.objects.all()
    template = loader.get_template('sachnr/dispo_all.html')
    if request.method == 'GET':
        form = DispoForm()
    elif request.method == 'POST':
        form = DispoForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('core:dispo_all'))
    else:
        form = DispoForm()
    return HttpResponse(template.render({'dispo_all': dispo_all, 'form': form}, request))


@permission_required('core.add_dispo')
def edit_dispo(request, pk):
    dispo_edit = Dispo.objects.get(id=pk)
    template = loader.get_template('sachnr/edit_dispo.html')
    if request.method == 'POST':
        form = DispoForm(request.POST, instance=dispo_edit)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:dispo_all'))
    else:
        form = SachnrForm(instance=dispo_edit)
        return HttpResponse(template.render({'form': form, 'dispo_edit': dispo_edit}, request))


@permission_required('core.add_dispo')
def dispo_delete(request, pk):
    dispo_delete = Dispo.objects.get(id=pk).delete()
    if request.method == 'POST':
        form = DispoForm(request.POST, instance=dispo_delete)
        form.u.delete()
        form.save()
    return HttpResponseRedirect(reverse('core:dispo_all'))


def serialize_deliverer(request):
    all_deliverers = Deliverer.objects.values('id', 'number', 'name')
    json_serializer = json.dumps(list(all_deliverers))
    return HttpResponse(json_serializer, content_type='application/json')


def serialize_supplier(request):
    all_suppliers = Supplier.objects.values('id', 'name')
    json_serializer = json.dumps(list(all_suppliers))
    return HttpResponse(json_serializer, content_type='application/json')

core/templates/sachnr/dispo_all.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Dispo</title>
   <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="/static/datables/datatables.min.css">
		<script type="text/javascript" src="/static/js/bootstrap.js.map"></script>
		<script type="text/javascript" src="/static/datables/datatables.min.js"></script>

</head>
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#tabela').dataTable({

                });
			} );
		</script>
<body>
<br/>
<p><a href="{% url 'core:main' %}" type="button" class="btn btn-outline-primary">main page</a></p>

<table class="table table-striped table-bordered" id="tabela">
	<thead>
		<tr>
			<th>dispo</th>
            <th>ekg</th>
            <th>usuń</th>
        </tr>
	</thead>
	<tbody>
    {% for n in dispo_all %}
		<tr>
            <td>{{ n.name }}
                <a href="{% url 'core:edit_dispo' pk=n.id %}"><i class="fa fa-edit"></i></a>
            </td>
            <td>{{ n.ekg }}</td>
            <td><a href="{% url 'core:dispo_delete' pk=n.id %}"><i class="fa fa-trash-alt"></i></a></td>

		</tr>
    {% endfor %}
</table>
<div class="col-md-4 column">
<form method="post">
    {% csrf_token %}
<p><label for="id_name">Name:</label>
    <input class="form-control" id="id_name" maxlength="25" name="name" type="text"></p>
<p><label for="id_ekg">Ekg:</label>
    <input class="form-control" id="id_ekg" maxlength="25" name="ekg" type="text"></p>
    <button class="btn btn-primary" type="submit">Zapisz</button>
    <a href="{% url 'core:main' %}" type="button" class="btn btn-secondary">Anuluj</a>
</form>
    </div>

</body>
</html>
{% endblock %}

core/templates/sachnr/disponent_all.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of responsibles</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />

<!-- datatables -->
<link rel="stylesheet" type="text/css" href="/static/datables/datatables.min.css">
<script type="text/javascript" src="/static/datables/datatables.js"></script>
<script type="text/javascript" src="/static/js/scripts.js"></script>

<!-- select 2 -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<script type="text/javascript" src="/static/js/selectize.js"></script>


		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#tabela').dataTable({

                });
			} );
		</script>
        <script type="text/javascript">
        $(document).ready(function() {
                $(".select2").selectize( {
                    plugins: ['remove_button']
                });
            });
        </script>
        <script type="text/javascript">
        $(document).ready(function() {
                $(".select").selectize( {
                });
            });
        </script>

</head>
<body>
<table class="table table-striped table-bordered" id="tabela">
	<thead>
		<tr>
			<th>dispo</th>
            <th>shortsign</th>
            <th>delete</th>
        </tr>
	</thead>
	<tbody>
    {% for n in all %}
		<tr>
            <td>{% for x in n.dispo.all %}{{ x }}{% endfor %}
                <a href="{% url 'core:edit_disponent' pk=n.id %}"><i class="fa fa-edit"></i></a></td>
        	<td>{{ n.shortsign }}</td>
            <td><a href="{% url 'core:delete_disponent' pk=n.id %}"><i class="fa fa-trash-alt"></i></a></td>
		</tr>
    {% endfor %}
</table>

<div class="col-md-4 column">
<form method="post">
    {% csrf_token %}
    <p><label for="id_shortsign">shortsign:</label>
    <select class="select" id="id_shortsign" name="shortsign">
        <option value>shortsign</option>
        {% for n in users %}
            <option value="{{ n.id }}">{{ n.username }}</option>
        {% endfor %}
    </select></p>
    <p><label for="id_dispo">dispo:</label>
    <select class="select2" id="id_dispo" name="dispo" multiple="multiple">
            {% for n in dispo %}
                <option value="{{ n.id }}">{{ n.name }} {{ n.ekg }}</option>
            {% endfor %}
    </select></p>

    <p><input class="btn btn-primary" type="submit" value="save">
    <a href="{% url 'core:main' %}" type="button" class="btn btn-secondary">cancel</a></p>
</form>
</div>

</body>
</html>
{% endblock %}

core/templates/sachnr/edit.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit form</title>
    <!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script type="text/javascript" src="/static/js/selectize.js"></script>
</head>
<body>
<script>
    $(document).ready(function() {
                $(".selectize").selectize({
                width: 400

                });
            });
</script>
<div class="col-md-4 column">
    <form method='post' class="edit">

{% csrf_token %}
<p>
    <label for="id_sachnr">Sachnr:</label>
    <input class="form-control" id="id_sachnr" maxlength="50" name="sachnr" type="text" value="{{ edit.sachnr }}" contenteditable="true">
</p>

<p>
    <label for="id_description">Description:</label>
    <input class="form-control" id="id_description" maxlength="200" name="description" type="text" value="{{ edit.description }}">
</p>

<p>
    <label for="id_dispo">Dispo:</label>
        <select class="selectize" id="id_dispo" name="dispo">
        <option selected="selected" value="{{ edit.dispo_id }}">{{ edit.dispo.ekg }} {{ edit.dispo.name }}</option>
        {% for n in dispo %}
            <option value="{{ n.id }}">{{ n.name }} {{ n.ekg }}</option>
        {% endfor %}
    </select>
</p>

    <button class="btn btn-primary" type="submit">save</button>
    <a href="{% url 'core:sachnr_select_detailed_view' %}" type="button" class="btn btn-secondary">cancel</a>
{% if perms.core.delete %}
    <a href="{% url 'core:delete_sachnr' edit.id %}" type="button" class="btn btn-danger">usuń</a>
{% endif %}
</form>
<br>
{% if sachnr_disponent %}
    <p>
        <label>person responsible:</label>

    {% for n in sachnr_disponent %}
        <input class="form-control" maxlength="200" type="text" disabled value="{{ n.shortsign }}"></p>
    {% endfor %}
{% endif %}

</div>
</body>
</html>
{% endblock %}

core/templates/sachnr/edit_dispo.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit</title>
</head>
<body>
<div class="col-md-4 column">
    <form method='post' class="edit">

{% csrf_token %}

<p><label for="id_name">Dispo:</label>
    <input class="form-control" id="id_name" name="name" type="text" value="{{ dispo_edit.name }}"></p>
<p><label for="id_ekg">ekg:</label>
    <input class="form-control" id="id_ekg" name="ekg" type="text" value="{{ dispo_edit.ekg }}"></p>

    <button class="btn btn-primary" type="submit">save</button>
    <a href="{% url 'core:dispo_all' %}" type="button" class="btn btn-secondary">cancel</a>
    <a href="{% url 'core:dispo_delete' dispo_edit.id %}" type="button" class="btn btn-danger">delete</a>
</form>
</div>
</body>
</html>
{% endblock %}

core/templates/sachnr/import.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">save</button>
    <a href="{% url 'core:main' %}" type="button" class="btn btn-info">Anuluj</a>
</form>

</body>
</html>
{% endblock %}

core/templates/sachnr/sachnr_detailed_view.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sachnr podgląd szczegółów</title>
<!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script type="text/javascript" src="/static/js/selectize.js"></script>


</head>

<body>
<a type="button" class="btn btn-outline-secondary" href = {% url 'core:main' %}>Back</a>

<div>
<h5>Select Sachnummer:</h5>
    <select id="sachnr" style="width: 400px"></select>

</div>

<script>
    var $sachnr = $('#sachnr').selectize({
            valueField: 'sachnr',
            labelField: 'sachnr',
            searchField: 'sachnr',
            options: [{}],
            maxOptions: 5,
            loadThrottle: 100,
            load: function (query, callback) {
                if (!query.length) return callback();
                $.ajax({
                    url: "{% url 'core:serialize_sachnr' %}",
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        name: query
                        },
                    error: function() {
                        callback();
                    },
                    success: function(res) {
                        callback(res);

                    }
            })
            },
            onChange: function(value) {
                var id = value;
                var url = '{% url 'core:edit_sachnr' 0 %}';
                url = url.replace(0, id);
                document.getElementById("link").setAttribute("href", url);

            }
        });
</script>

<a id="link" type="button" class="btn btn-success">wyświetl szczegóły</a>
</body>
</html>
{% endblock %}

core/templates/sachnr/sachnr_serialize.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<script type="text/javascript">
    accounts_array = {{ json_serializer|safe }};
</script>


</body>
</html>

core/templates/sachnr/show_all.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    {% load dispo %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sachnummer</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<!-- jQuery -->
<script type="text/javascript" charset="utf8" src="/static/js/jquery-3.4.1.min.js"></script>
<!-- selectize CSS -->
<link rel="stylesheet" href="/static/css/selectize.css"/>
<!--selectize JS -->
<script type="text/javascript" src="/static/js/selectize.js"></script>

</head>
<body>
<br/>
{% if perms.core.add_sachnr %}
<p><a href="{% url 'core:import_data' %}" type="button" class="btn btn-primary">import</a></p>
<p>
    <a href="{% url 'core:dispo_all' %}" type="button" class="btn btn-primary">dispo</a>
    <a href="{% url 'core:disponent_all' %}" type="button" class="btn btn-primary">responsibles</a>
{% endif %}
    <a href="{% url 'core:sachnr_select_detailed_view' %}" type="button" class="btn btn-primary">check sachnummer details</a>
</p>

<script>
    $(document).ready(function() {
                $(".selectize").selectize({
                width: 400

                });
            });
</script>
<div class="col-md-4 column">
{% if perms.core.add_sachnr %}
<form method='post' class="edit">
{% csrf_token %}
<p><label for="id_sachnr">Sachnr:</label>
    <input class="form-control" id="id_sachnr" maxlength="50" name="sachnr" type="text"></p>
<p><label for="id_description">description:</label>
    <input class="form-control" id="id_description" maxlength="200" name="description" type="text"></p>
<p><label for="id_dispo">Dispo:</label>
    <select class="selectize" id="id_dispo" name="dispo">
<option value="" selected="selected">---------</option>
        {% for n in dispo %}
<option value="{{ n.id }}">{{ n.name }} {{ n.ekg }} {% if request.user.username != 'admin' %}{{ n.pk|disponent_name|cut:"[(u'"|cut:"',),"|cut:"(u'"|cut:"',)]" }}{% endif %}</option>
        {% endfor %}
</select></p>

    <button class="btn btn-primary" type="submit">save</button>
    <button class="btn btn-secondary">cancel</button>
<p style="color:red">{{ info }}</p>
</form>
{% endif %}
</div>
{{ a }}
</body>
</html>
{% endblock %}